{{- if .Values.externalSecrets.credentials.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "timescaledb.fullname" . }}-credentials
spec:
{{- with .Values.externalSecrets.credentials }}
  refreshInterval: {{ .refreshInterval | quote }}
  secretStoreRef:
    name: {{ .secretStoreName | quote }}
    kind: {{ default "SecretStore" .secretStoreKind | quote }}
  target:
    name: {{ $.Values.timescaledb_single.secrets.credentialsSecretName }}
  {{- with .data }}
  data:
    {{- . | toYaml | nindent 2 }}
  {{- end }}
{{ end }}
{{- end }}
