apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "timescaledb.fullname" . }}
  labels:
{{ include "timescaledb-helm.labels" . | indent 4}}
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: {{ include "timescaledb.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "timescaledb.fullname" . }}-fix
