apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "timescaledb.fullname" . }}-fix
  labels:
{{ include "timescaledb-helm.labels" . | indent 4}}
    app.kubernetes.io/component: rbac
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
